/** @type {import('tailwindcss').Config} */
const defaultTheme = require("tailwindcss/defaultTheme");
const { createThemes } = require("tw-colors");

module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],

  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter var", ...defaultTheme.fontFamily.sans],
      },
      colors: {
        tab: "hsl(0 0% 43.5%)",
        tabHover: "hsl(0 0% 9%)",
        pizza: "rgb(var(--color-primary) / <alpha-value>)",
        burger: "rgb(var(--color-secondary) / <alpha-value>)",
      },
    },
  },
  plugins: [
    createThemes({
      light: {
        "btn-primary": "#fff",
        "btn-secondary": "#000",
        "nav-scroll": "hsla(0,0%,100%,0.75)",
        "nav-shadow": "rgba(0,0,0,0.1)",
        "nav-item-primary": "#666",
        "nav-item-secondary": "#000",
        'logo': "#000",
        'background': "#fff",
        "geist-background": "#fff",
        "accents-1": "#fafafa",
        "accents-2": "#eaeaea",
        "accents-3": "#999",
        "accents-4": "#888",
        "accents-5": "#666",
        "accents-6": "#444",
        "accents-7": "#333",
        "accents-8": "#111",
        "geist-foreground": "#000",
        "geist-error-lighter": "#f7d4d6",
        "geist-error-light": "#ff1a1a",
        "geist-error": "#e00",
        "geist-error-dark": "#c50000",
        "geist-success-lighter": "#d3e5ff",
        "geist-success-light": "#3291ff",
        "geist-success": "#0070f3",
        "geist-success-dark": "#0761d1",
        "geist-warning-lighter": "#ffefcf",
        "geist-warning-light": "#f7b955",
        "geist-warning": "#f5a623",
        "geist-warning-dark": "#ab570a",
        "geist-violet-lighter": "#d8ccf1",
        "geist-violet-light": "#8a63d2",
        "geist-violet": "#7928ca",
        "geist-violet-dark": "#4c2889",
        "geist-cyan-lighter": "#aaffec",
        "geist-cyan-light": "#79ffe1",
        "geist-cyan": "#50e3c2",
        "geist-cyan-dark": "#29bc9b",
        "geist-highlight-purple": "#f81ce5",
        "geist-highlight-magenta": "#eb367f",
        "geist-highlight-pink": "#ff0080",
        "geist-highlight-yellow": "#fff500",
        "theme-toggle": "#fff",
        "geist-experimental": "#ebebeb",
        "geist-menu-button": "#e7e7e7",
        "geist-badge": "#2b2b2b",
      },
      dark: {
        "btn-primary": "#000",
        "btn-secondary": "#fff",
        "nav-scroll": "rgba(0,0,0,0.75)",
        "nav-shadow": "rgba(255,255,255,0.1)",
        "nav-item-primary": "#888",
        "nav-item-secondary": "#ededed",
        'logo': "#fff",
        "geist-background": "#000000",
        "accents-1": "#111111",
        "accents-2": "#333",
        "accents-3": "#444444",
        "accents-4": "#666666",
        "accents-5": "#888888",
        "accents-6": "#999999",
        "accents-7": "#eaeaea",
        "accents-8": "#fafafa",
        "geist-foreground": "#ffffff",
        "geist-error-lighter": "#f7d4d6",
        "geist-error-light": "#ff3333",
        "geist-error": "#ff0000",
        "geist-error-dark": "#e60000",
        "geist-success-lighter": "#d3e5ff",
        "geist-success-light": "#3291ff",
        "geist-success": "#0070f3",
        "geist-success-dark": "#0761d1",
        "geist-warning-lighter": "#ffefcf",
        "geist-warning-light": "#f7b955",
        "geist-warning": "#f5a623",
        "geist-warning-dark": "#ab570a",
        "geist-violet-lighter": "#d8ccf1",
        "geist-violet-light": "#8a63d2",
        "geist-violet": "#7928ca",
        "geist-violet-dark": "#4c2889",
        "geist-cyan-lighter": "#aaffec",
        "geist-cyan-light": "#79ffe1",
        "geist-cyan": "#50e3c2",
        "geist-cyan-dark": "#29bc9b",
        "geist-highlight-purple": "#f81ce5",
        "geist-highlight-magenta": "#eb367f",
        "geist-highlight-pink": "#ff0080",
        "geist-highlight-yellow": "#fff500",
        "theme-toggle": "#333333",
        "geist-experimental": "#171717",
        "geist-menu-button": "#191919",
        "geist-badge": "#a3a3a3",
      },
    }),
  ],
};
